addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
      - libboost1.55-all-dev 
language: cpp
compiler: gcc
script:
- cd build/release/src
- make -j8